### ISSUE TITLE
Google Ads API returns "user identifiers not supported" partial failure when value for user identifier is null (or undefined) 

### ISSUE THREAD

**Issue by cameronbourke** [stape-io/gads-offline-conversion-tag#16] opened 2024-04-12 02:08 UTC
## Context
We have downloaded the [Google Ads Offline Conversion](https://github.com/stape-io/gads-offline-conversion-tag) tag and configured it as a _Tag Template_. We then have an instance of the tag that is configured to send a phone number along with the conversion. This is achieved by adding property for `Phone` under the _User Data_ field.

## Steps to Reproduce
1. Create an instance of the Google Ads Offline Conversion tag.
2. Add at least one User property under the _User Data_ field.
3. Trigger the tag where the value for that property is `null`.

## Expected Behaviour
The tag does send the `hashedPhoneNumber` to the Google Ads API.

## Actual Behaviour
The value for `hashedPhoneNumber` is `null` which is then sent to the Google Ads API. This then appears to cause a partial failure since the the only valid type for the `hashedPhoneNumber` on the the type [UserIdentifier](https://developers.google.com/google-ads/api/reference/rpc/v16/UserIdentifier) is `string`.

To demonstrate this, consider the two cases for the `hashedPhoneNumber` property.

**Case 1**
The first case is where the value is `null`. Here we can see the value `null` for `hashedPhoneNumber` and the Google Ads API returns an error saying that this user identifier is not supported.

| GTM Tag Overview | Google Ads API Partial Error |
|-------------|--------------|
| ![01_phone_null_tag_overview](https://github.com/stape-io/gads-offline-conversion-tag/assets/7464366/667d0cec-bc0a-40ef-a25d-45493d03df54) | ![02_phone_null_error](https://github.com/stape-io/gads-offline-conversion-tag/assets/7464366/8603a8bd-2b4f-4c18-beda-fde46f4a5e7e) |

**Case 2**
The second case is where the value is not `null`. Here we can see the value `+61411111111` for `hashedPhoneNumber` and the Google Ads API no longer returns an error about the user identifier not being supported. Instead, we receive an expected error since this phone number does not have an associated ad click event.

| GTM Tag Overview | Google Ads API Partial Error |
|-------------|--------------|
| ![03_phone_valid_tag_overview](https://github.com/stape-io/gads-offline-conversion-tag/assets/7464366/ea8b812d-27e2-41b1-bd30-d648d97baf90) | ![04_phone_valid_tag_no_error](https://github.com/stape-io/gads-offline-conversion-tag/assets/7464366/262a23ad-219b-4a1b-8fa9-8066804890ae) |

## Possible Solution
One work-around that we've found to be effective is by skipping any user identifiers that have the value `null` or `undefined` in the function `addUserIdentifiers`.

![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/7464366/3a5bbc85-467a-4108-91e0-23a11be9c596)

**Comment by Bukashk0zzz** [comment] 2024-04-13 12:46
Thanks for the such nice bug report.
We will fix this issue next week.

**Comment by cameronbourke** [comment] 2024-04-24 07:25
@Bukashk0zzz No worries at all! Thanks for jumping on the issue.

**Comment by kHorozhanov** [comment] 2024-04-24 19:39
Duplicate of #14

**Comment by kHorozhanov** [comment] 2024-04-24 19:42
Hi @cameronbourke can you please try to update the tag to a latest version please? This issue should be already fixed.

**Closed as completed** 2024-04-29 12:08 UTC
